name: Secrets and Environments
on:
  workflow_dispatch:
env:
  WORKFLOW_ENV: I_AM_A_WORKFLOW_ENVIRONMENT_VARIABLE
jobs:
  job-1:
    name: Job 1
    runs-on: ubuntu-24.04
    env:
      JOB_ENV: I_AM_A_JOB_ENVIRONMENT_VARIABLE
    steps:
      - name: PRINT VARIABLES FOR TESTING

        env:
          STEP_ENV: I_AM_A_STEP_ENVIRONMENT_VARIABLE
          R: ${{ secrets.R }}
          V: ${{ vars.V }}
        run: |
          echo "Workflow env: $WORKFLOW_ENV"
          echo "Job env: $JOB_ENV"
          echo "Step env: $STEP_ENV"
          echo "R: ${R:-<UNSET>}
          echo "V: ${V:-<UNSET>}
      
#     env:
#       # Inject repository-level secret & variable into the shell
#       EXAMPLE_REPOSITORY_SECRET:
#       # Inject environment-level items into the shell
#     steps:
#       - name: Inspect values inside job
#         run: |
#           echo "Repo secret (masked):    $EXAMPLE_REPOSITORY_SECRET"
#           echo "Repo variable:           $EXAMPLE_REPOSITORY_VARIABLE"
#           echo "Env secret (masked):     $EXAMPLE_ENVIRONMENT_SECRET"
#           echo "Env variable:            $EXAMPLE_ENVIRONMENT_VARIABLE"

#   production-environment:
#     runs-on: ubuntu-24.04
#     environment: production
#     env:
#       # Inject repository-level secret & variable into the shell
#       EXAMPLE_REPOSITORY_SECRET:
#       EXAMPLE_REPOSITORY_VARIABLE: 
#       # Inject environment-level items into the shell
#       EXAMPLE_ENVIRONMENT_SECRET:
#       EXAMPLE_ENVIRONMENT_VARIABLE:
#     steps:
#       - name: Inspect values inside job
#         run: |
#           echo "Repo secret (masked):    $EXAMPLE_REPOSITORY_SECRET"
#           echo "Repo variable:           $EXAMPLE_REPOSITORY_VARIABLE"
#           echo "Env secret (masked):     $EXAMPLE_ENVIRONMENT_SECRET"
#           echo "Env variable:            $EXAMPLE_ENVIRONMENT_VARIABLE"



